### ISSUE TITLE
site 'name' and site 'ref' clarification

### ISSUE THREAD

**Issue by RainfallNZ** [tethys-ts/tethysts#12]
Hi Mike,  
This is just a comment that you will be well aware of, but I thought worth noting while I remembered it.  
There appears to be three different approaches to providing site names for streamflow sites.  

1. Otago and Southland streamflow sites have names as a 'ref' attribute.  
2. Canterbury and NIWA have names in a 'name' attribute.  
3. The NIWA 'name' attribute includes the 'ref' string in brackets at the end of the 'name' string. 

This is an issue because a site name is a very common approach to searching for data and, in the case of Otago and Southland, it is the only non-geographic unique reference that could be related back to council source data.  
Currently , to match a site name, it would be necessary to search both 'ref' and 'name' fields, and to parse the NIWA 'name's.  
It would be good if 'name' fields could be added to the Otago and Southland data as duplicates to the 'ref' fields.  
It would be good if the NIWA site names could have the suffixed numbers removed.

Something for you to consider, but I can't imagine it being a priority.

Cheers

Tim

**Comment by mullenkamp** [comment]
Thanks Tim. I totally agree. This has bothered me a bit for a while now actually. 
The current state for the organisations that you mention is due to the different systems that each one has. With Hilltop systems, many organisations use the name as the unique reference identifier, while others use a semi-generated reference number as the reference identifier and have the site names seperate.

This is a relatively easy fix and something that I feel is necessary for consistancy (and I like consistancy).
I'll get to this next week.
Thanks again.

**Comment by mullenkamp** [comment]
I think the issue has been resolved.
